"""empty message

Revision ID: 5b86fb9a43f3
Revises: 6fcd22cc6cb9
Create Date: 2022-07-04 23:57:41.322811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b86fb9a43f3'
down_revision = '6fcd22cc6cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_user_id', table_name='scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scores_user_id', 'scores', ['user_id'], unique=False)
    # ### end Alembic commands ###
