"""empty message

Revision ID: 784e1d58c557
Revises: 5b86fb9a43f3
Create Date: 2022-07-05 07:30:03.695083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784e1d58c557'
down_revision = '5b86fb9a43f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('position', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'position')
    # ### end Alembic commands ###
